services:
  php:
    build: 
      dockerfile: ./infra/php/Dockerfile
      context: .
    volumes:
      - ./src:/var/www/html
    networks:
      - quotter

  web:
    build: 
      dockerfile: ./infra/web/Dockerfile
      context: .
    ports:
      - 8080:80
    volumes:
      - ./src/public:/var/www/html/public
      - ./infra/web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - quotter
    depends_on:
      - php #php-fpmと通信するためphpコンテナの後に起動する必要がある

  db:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravel
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - quotter

volumes:
  data:
networks:
  quotter:
    driver: bridge